<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GPCGeometry\GPCGeometry.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="GPCUtilities">
      <HintPath>..\..\Utilities\GPCUtilities\bin\Release\netstandard2.0\GPCUtilities.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
